app:
  name: "Todo Service"
  environment: "development"
  port: 8080
  host: "0.0.0.0"

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "your-username"
  password: "your-password"
  name: "your-database-name"
  ssl_mode: "disable"

swagger:
  enabled: true
  path: "/swagger"
  doc_path: "/swagger/index.html"

api:
  base_url: "http://localhost:8080/api/v1"
  timeout: 30

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://yourfrontenddomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
